apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: us-east1
  name: category-app
  namespace: '544023292904'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 466.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: xxccmzshou
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - image: us-east1-docker.pkg.dev/category-app-416218/cloud-run-source-deploy/category-app@sha256:d6600847d46b11f61e004d2efcd98ddf43aee6cacd1c3fb2096f15abd305ca62
        env:
        - name: OPENAI_KEY
          value: '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'
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 544023292904-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
